devmgr/Models/FLOW_PROJECT.cs
namespace devmgr.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Linq;
    public partial class FLOW_PROJECT
    {
        public int id { get; set; }

        [StringLength(30)]
        [Display(Name = "项目编号")]
        public string code { get; set; }
        [Display(Name = "所属产品")]
        public int? productid_fx { get; set; }
        [Display(Name = "项目负责人")]
        public int? responserid_fx { get; set; }
        [Display(Name = "起始日期")]
        [Column(TypeName = "date")]
        public DateTime? startdate { get; set; }
        [Display(Name = "截止日期")]
        [Column(TypeName = "date")]
        public DateTime? deadline { get; set; }

        [StringLength(500)]
        [Display(Name = "内 容")]
        public string request_text { get; set; }

        [StringLength(1000)]
        [DataType(DataType.MultilineText)]
        [Display(Name = "相关文档")]
        public string request_file { get; set; }
        [Display(Name = "所属项目")]
        public int? dad_projectid_fx { get; set; }
        [Display(Name = "项目等级")]
        public int? dad_level { get; set; }
        [Display(Name = "是否最终项目")]
        public int? is_bottom { get; set; }

        [StringLength(100)]
        [Display(Name = "名 称")]
        public string desc_text { get; set; }

        [StringLength(200)]
        [Display(Name = "备 注")]
        public string remark { get; set; }
        [Display(Name = "创建者")]
        public int? whocreateid_fx { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "创建日期")]
        public DateTime? createdate { get; set; }
        static public List<FLOW_PROJECT> GETALL()
        {
            Model1 db = new Model1();
            return db.FLOW_PROJECT.ToList();
        }
    }
}

devmgr/Controllers/FLOW_PROJECTController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using devmgr.Models;
using PagedList;

namespace devmgr.Controllers
{
    public class FLOW_PROJECTController : Controller
    {
        private Model1 db = new Model1();

        // GET: FLOW_PROJECT
        public ActionResult Index(int? pageNum,string searchName, int? searchProd,string sortOrder, int? mistatus)
        {
            List<FLOW_PRODUCT> categories_prod = FLOW_PRODUCT.GETALL();
            ViewData["categories_prod"] = new SelectList(categories_prod, "id", "name");

            ViewBag.CurrentSort = sortOrder;
            ViewBag.CodeSortParm = sortOrder == "Code_asc" ? "Code_desc" : "Code_asc";
            ViewBag.CreatedateSortParm = sortOrder == "date_asc" ? "date_desc" : "date_asc";

            var projects = from s in db.FLOW_PROJECT
                           select s;
            //#########################################################
            if (Request.Cookies["islogin"] == null)
            {
                Response.Redirect("/Account/Login");
            }
            Model1 ef = new Model1();
            string caid = Request.Cookies["username"].Value.ToString();
            int cuid = ef.SYS_USER.Where(item => item.account_id == caid).First<SYS_USER>().id;
            int? ugid = int.Parse(ef.SYS_USER.Where(item => item.account_id == caid).First<SYS_USER>().usertypeid_fx.ToString());
            int mod1id = ef.SYS_MODULE.Where(item => item.code == "MOD00002").First<SYS_MODULE>().id;
            var obj = ef.SYS_UTYPE_MODULE.Where(item => item.usertypeid_fx == ugid && item.moduleid_fx == mod1id);
            if (obj.First<SYS_UTYPE_MODULE>().isenable == 0)
            {
                //START:与我相关的项目
                var products = from s in db.FLOW_PRODUCT
                               select s;
                products = products.Where(s => s.whocreateid_fx == cuid|| s.Responserid_fx == cuid);
                //END:与我相关的项目
                var productids = from s in products
                               select s.id;

                int[] pdids = productids.ToArray();
                projects = from s in projects
                           where s.whocreateid_fx == ugid || s.responserid_fx ==ugid || productids.Contains((int)s.productid_fx)
                           select s;
            }

            if (mistatus == 1)
            {//我创建的
                projects = projects.Where(s => s.whocreateid_fx == cuid);
            }
            if (mistatus == 0)
            {//我负责的
                projects = projects.Where(s => s.responserid_fx == cuid);
            }
            //###########################################################

            if (searchProd != null)
            {//项目筛选
                projects = projects.Where(s => s.productid_fx == searchProd);
            }
            if (!String.IsNullOrEmpty(searchName))
            {//搜索名称
                projects = projects.Where(s => s.desc_text.Contains(searchName));
            }

            switch (sortOrder)
            {
                case "Code_desc":
                    projects = projects.OrderByDescending(s => s.code);
                    break;
                case "Code_asc":
                    projects = projects.OrderBy(s => s.code);
                    break;
                case "date_asc":
                    projects = projects.OrderBy(s => s.createdate);
                    break;
                case "date_desc":
                    projects = projects.OrderByDescending(s => s.createdate);
                    break;
                default:
                    projects = projects.OrderBy(s => s.createdate);
                    break;
            }

            return View(projects.ToPagedList(pageNum ?? 1, 5));
        }

        // GET: FLOW_PROJECT/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FLOW_PROJECT fLOW_PROJECT = db.FLOW_PROJECT.Find(id);
            if (fLOW_PROJECT == null)
            {
                return HttpNotFound();
            }
            return View(fLOW_PROJECT);
        }

        // GET: FLOW_PROJECT/Create
        public ActionResult Create()
        {
            List<SYS_USER> categories_user = SYS_USER.GETALL();
            ViewData["Categories_user"] = new SelectList(categories_user, "id", "cname");

            List<FLOW_PRODUCT> categories = FLOW_PRODUCT.GETALL();
            ViewData["Categories_prod"] = new SelectList(categories, "id", "name");
            return View();
        }

        // POST: FLOW_PROJECT/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,code,productid_fx,responserid_fx,startdate,deadline,request_text,request_file,dad_projectid_fx,dad_level,is_bottom,desc_text,remark,whocreateid_fx,createdate")] FLOW_PROJECT fLOW_PROJECT)
        {
            Model1 ef = new Model1();
            String username = Request.Cookies["username"].Value.ToString();
            String cuuserid = ef.SYS_USER.Where(item => item.account_id == username).First<SYS_USER>().id.ToString();
            var obj = ef.FLOW_PROJECT.Where(item => item.id >= 0);
            int nowcode = 0, maxid = 0;
            if (obj.Count<FLOW_PROJECT>() > 0)
            {
                maxid = obj.Max(item => item.id);
                nowcode = maxid + 1;
            }
            else
            {
                nowcode = 1;
            }

            fLOW_PROJECT.code = "PRJ" + nowcode.ToString().PadLeft(5, '0');
            fLOW_PROJECT.createdate = DateTime.Now;
            fLOW_PROJECT.whocreateid_fx = int.Parse(cuuserid);
            if (ModelState.IsValid)
            {
                db.FLOW_PROJECT.Add(fLOW_PROJECT);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            List<SYS_USER> categories_user = SYS_USER.GETALL();
            ViewData["Categories_user"] = new SelectList(categories_user, "id", "cname");

            List<FLOW_PRODUCT> categories = FLOW_PRODUCT.GETALL();
            ViewData["Categories_prod"] = new SelectList(categories, "id", "name");
            return View(fLOW_PROJECT);
        }

        // GET: FLOW_PROJECT/Edit/5
        public ActionResult Edit(int? id)
        {
            List<SYS_USER> categories_user = SYS_USER.GETALL();
            ViewData["Categories_user"] = new SelectList(categories_user, "id", "cname");

            List<FLOW_PRODUCT> categories = FLOW_PRODUCT.GETALL();
            ViewData["Categories_prod"] = new SelectList(categories, "id", "name");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FLOW_PROJECT fLOW_PROJECT = db.FLOW_PROJECT.Find(id);
            if (fLOW_PROJECT == null)
            {
                return HttpNotFound();
            }
            return View(fLOW_PROJECT);
        }

        // POST: FLOW_PROJECT/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,code,productid_fx,responserid_fx,startdate,deadline,request_text,request_file,dad_projectid_fx,dad_level,is_bottom,desc_text,remark,whocreateid_fx,createdate")] FLOW_PROJECT fLOW_PROJECT)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fLOW_PROJECT).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            List<SYS_USER> categories_user = SYS_USER.GETALL();
            ViewData["Categories_user"] = new SelectList(categories_user, "id", "cname");

            List<FLOW_PRODUCT> categories = FLOW_PRODUCT.GETALL();
            ViewData["Categories_prod"] = new SelectList(categories, "id", "name");
            return View(fLOW_PROJECT);
        }

        // GET: FLOW_PROJECT/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FLOW_PROJECT fLOW_PROJECT = db.FLOW_PROJECT.Find(id);
            if (fLOW_PROJECT == null)
            {
                return HttpNotFound();
            }
            return View(fLOW_PROJECT);
        }

        // POST: FLOW_PROJECT/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FLOW_PROJECT fLOW_PROJECT = db.FLOW_PROJECT.Find(id);
            db.FLOW_PROJECT.Remove(fLOW_PROJECT);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

devmgr/Views/FLOW_PROJECT/Create.cshtml
@model devmgr.Models.FLOW_PROJECT

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>添加</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>项目管理</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.code, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group">
            @Html.LabelFor(model => model.desc_text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.desc_text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.desc_text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.productid_fx, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.productid_fx, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productid_fx, "", new { @class = "text-danger" })*@
                @{SelectList category = (SelectList)ViewData["Categories_prod"];}
                @Html.DropDownListFor(model => model.productid_fx, category, "--请选择--", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.responserid_fx, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.responserid_fx, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.responserid_fx, "", new { @class = "text-danger" })*@
                @{SelectList categoryuser = (SelectList)ViewData["categories_user"];}
                @Html.DropDownListFor(model => model.responserid_fx, categoryuser, "--请选择--", new { htmlAttributes = new { @class = "form-control" } })


            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.startdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.startdate, new { htmlAttributes = new { @class = "form-control",id = "datepicker1" } })
                @Html.ValidationMessageFor(model => model.startdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deadline, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deadline, new { htmlAttributes = new { @class = "form-control",id = "datepicker2" } })
                @Html.ValidationMessageFor(model => model.deadline, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.request_text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.request_text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.request_text, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.request_file, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.request_file, new { htmlAttributes = new {} })
                @Html.ValidationMessageFor(model => model.request_file, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.dad_projectid_fx, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dad_projectid_fx, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dad_projectid_fx, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.dad_level, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.dad_level, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.dad_level, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.is_bottom, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.is_bottom, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.is_bottom, "", new { @class = "text-danger" })
            </div>
        </div>*@

        

        <div class="form-group">
            @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.whocreateid_fx, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.whocreateid_fx, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.whocreateid_fx, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.createdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.createdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.createdate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="添加" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回列表", "Index")
</div>
<script src="../../Scripts/pikaday.js"></script>
<script>
    var picker = new Pikaday(
    {
        field: document.getElementById('datepicker1'),
        firstDay: 1,
        minDate: new Date('2000-01-01'),
        maxDate: new Date('2020-12-31'),
        yearRange: [1950,2050]
    });
    var picker2 = new Pikaday(
    {
        field: document.getElementById('datepicker2'),
        firstDay: 1,
        minDate: new Date('2000-01-01'),
        maxDate: new Date('2020-12-31'),
        yearRange: [1950, 2050]
    });
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/ueditor-utf8/ueditor.config.js", "~/Scripts/ueditor-utf8/ueditor.all.js")
    <script type="text/javascript">
        var editor = new baidu.editor.ui.Editor({
        UEDITOR_HOME_URL: '/Scripts/ueditor-utf8/',//配置编辑器路径   也可以在ueditor.config.js文件中配置。
        iframeCssUrl: '/Scripts/ueditor-utf8/themes/iframe.css',//样式路径
        // initialContent:'欢迎使用ueditor',//初始化编辑器内容
        autoHeightEnabled:true,//高度自动增长
        initialFrameHeight:400  //配置编辑器的初始高度为400px。
        });
        editor.render('request_file');   //将编辑器装入 ID=Content 的文本域中。
    </script>
}

devmgr/Views/FLOW_PROJECT/Index.cshtml
@*@model IEnumerable<devmgr.Models.FLOW_PROJECT>*@
@model PagedList.IPagedList<devmgr.Models.FLOW_PROJECT>
@using PagedList.Mvc;

@using System.Linq;
@using devmgr.Models;
@{Model1 ef = new Model1(); }


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>项目管理</h2>

<p>
    @Html.ActionLink("添 加", "Create")
</p>

<span style="background-color: rgb(255, 255, 102);">
    @using (Html.BeginForm("Index", "FLOW_PROJECT", FormMethod.Get, new { @class = "form-inline" }))
    {
        <p>
            项目名称: @Html.TextBox("searchName", null, new { @class = "form-control", @placeholder = "请输入关键字", @style = "width:150px;height:30px;font-size:12px;" })
            &nbsp;所属产品: @Html.DropDownList("searchProd", ViewData["categories_prod"] as SelectList, "请选择项目", new { @style = "width:150px;height:30px;font-size:12px;", @id = "searchProj" })
            &nbsp; &nbsp;  @Html.RadioButton("mistatus", 1) 由我创建 @Html.RadioButton("mistatus", 0) 由我负责 @Html.RadioButton("mistatus", 2, true) 全部
            &nbsp;<input type="submit" value="查询" class="btn btn-default" />
        </p>
    }

</span>

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("项目编号", "Index", new { sortOrder = ViewBag.CodeSortParm })
        </th>
        <th>
            项目名称
        </th>
        <th>
            所属产品
        </th>
        <th>
            项目负责人
        </th>
        <th>
            开始日期
        </th>
        <th>
            截止日期
        </th>
        @*<th>
        @Html.DisplayNameFor(model => model.request_text)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.request_file)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.dad_projectid_fx)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.dad_level)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.is_bottom)
    </th>*@
        
        @*<th>
            备注
        </th>*@
        <th>
            创建者
        </th>
        <th>
            @Html.ActionLink("创建日期", "Index", new { sortOrder = ViewBag.CreatedateSortParm })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.desc_text)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.productid_fx)
        </td>*@
        <td>
            @{ var obj = ef.FLOW_PRODUCT.Where(item1 => item1.id == item.productid_fx); }
            @if (obj.Count<FLOW_PRODUCT>() > 0)
            {
                @Html.Label(obj.First<FLOW_PRODUCT>().name.ToString())
            }
            else
            {

            }
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.responserid_fx)
        </td>*@

        <td>
            @{ var obj2 = ef.SYS_USER.Where(item1 => item1.id == item.responserid_fx); }
            @if (obj2.Count<SYS_USER>() > 0)
            {
                @Html.Label(obj2.First<SYS_USER>().cname.ToString())
            }
            else
            {

            }
        </td>

        <td>
            @Html.DisplayFor(modelItem => item.startdate, "shortdatetime")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.deadline, "shortdatetime")
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.request_text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.request_file)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dad_projectid_fx)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.dad_level)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.is_bottom)
        </td>*@
        
        @*<td>
            @Html.DisplayFor(modelItem => item.remark)
        </td>*@
        @*<td>
            @Html.DisplayFor(modelItem => item.whocreateid_fx)
        </td>*@
        <td>
            @{ var obj3 = ef.SYS_USER.Where(item1 => item1.id == item.whocreateid_fx); }
            @if (obj3.Count<SYS_USER>() > 0)
            {
                @Html.Label(obj3.First<SYS_USER>().cname.ToString())
            }
            else
            {


            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.createdate, "shortdatetime")
        </td>
        <td>
           @{
               if (Request.Cookies["islogin"] == null)
               {
                   if (ViewContext.RouteData.Values["controller"].ToString() == "Account" && ViewContext.RouteData.Values["action"].ToString() == "Login")
                   {
                   }
                   else
                   {
                       Response.Redirect("/Account/Login");
                   }
               }
               String caid = Request.Cookies["username"].Value.ToString();
               int cuid = ef.SYS_USER.Where(s => s.account_id == caid).First<SYS_USER>().id;
               int? ugid = int.Parse(ef.SYS_USER.Where(s => s.account_id == caid).First<SYS_USER>().usertypeid_fx.ToString());
               int mod1id = ef.SYS_MODULE.Where(s => s.code == "MOD00002").First<SYS_MODULE>().id;
               var objs = ef.SYS_UTYPE_MODULE.Where(s => s.usertypeid_fx == ugid && s.moduleid_fx == mod1id);
        }
        @if (objs.Count() != 0)
        {
            if (objs.First<SYS_UTYPE_MODULE>().iswrite == 1)
            {
                @Html.ActionLink("编辑 |", "Edit", new { id = item.id })
            }
        }
        @Html.ActionLink("查看", "Details", new { id = item.id })

        @if (objs.Count() != 0)
        {
            if (objs.First<SYS_UTYPE_MODULE>().iswrite == 1)
            {
                @Html.ActionLink("| 删除", "Delete", new { id = item.id })
            }
        }
        </td>
    </tr>
}

</table>

    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, pageNum => Url.Action("Index", new { pageNum, categories_prod = ViewData["categories_prod"], sortOrder = ViewBag.CurrentSort }))