devmgr/Models/FLOW_REQUEST.cs
namespace devmgr.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class FLOW_REQUEST
    {
        public int id { get; set; }

        [StringLength(30)]
        [Display(Name = "需求编号")]
        public string code { get; set; }
        [Display(Name = "所属产品")]
        public int? productid_fx { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "起始日期")]
        public DateTime? startdate { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "截止日期")]
        public DateTime? deadline { get; set; }

        [StringLength(500)]
        [Display(Name = "需求内容")]
        [DataType(DataType.MultilineText)]
        public string request_text { get; set; }

        [StringLength(1000)]
        [Display(Name = "相关文档")]
        public string request_file { get; set; }

        [StringLength(100)]
        [Display(Name = "描 述")]
        public string desc_text { get; set; }

        [StringLength(200)]
        [Display(Name = "备 注")]
        public string remark { get; set; }

        [Display(Name = "创建者")]
        public int? whocreateid_fx { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "创建日期")]
        public DateTime? createdate { get; set; }
    }
}

devmgr/Controllers/FLOW_REQUESTController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using devmgr.Models;
using PagedList;

namespace devmgr.Controllers
{
    public class FLOW_REQUESTController : Controller
    {
        private Model1 db = new Model1();

        // GET: FLOW_REQUEST
        public ActionResult Index(int? pageNum, int? searchProd, string sortOrder,int? mistatus)
        {
            var requests = from s in db.FLOW_REQUEST
                           select s;

            List<FLOW_PRODUCT> categories_prod = FLOW_PRODUCT.GETALL();
            ViewData["categories_prod"] = new SelectList(categories_prod, "id", "name");

            ViewBag.CurrentSort = sortOrder;
            ViewBag.CodeSortParm = sortOrder == "Code_asc" ? "Code_desc" : "Code_asc";
            ViewBag.CreatedateSortParm = sortOrder == "date_asc" ? "date_desc" : "date_asc";

            //#########################################################
            if (Request.Cookies["islogin"] == null)
            {
                Response.Redirect("/Account/Login");
            }
            Model1 ef = new Model1();
            string caid = Request.Cookies["username"].Value.ToString();
            int cuid = ef.SYS_USER.Where(item => item.account_id == caid).First<SYS_USER>().id;
            int? ugid = int.Parse(ef.SYS_USER.Where(item => item.account_id == caid).First<SYS_USER>().usertypeid_fx.ToString());
            int mod1id = ef.SYS_MODULE.Where(item => item.code == "MOD00011").First<SYS_MODULE>().id;
            var obj = ef.SYS_UTYPE_MODULE.Where(item => item.usertypeid_fx == ugid && item.moduleid_fx == mod1id);
            if (obj.First<SYS_UTYPE_MODULE>().isenable == 0)
            {
                //START:与我相关的项目
                var products = from s in db.FLOW_PRODUCT
                               select s;
                products = products.Where(s => s.whocreateid_fx == cuid || s.Responserid_fx == cuid);
                //END:与我相关的项目
                var productids = from s in products
                                 select s.id;

                int[] pdids = productids.ToArray();
                requests = from s in requests
                           where s.whocreateid_fx == ugid || productids.Contains((int)s.productid_fx)
                           select s;
            }

            if (mistatus == 1)
            {//我创建的
                requests = requests.Where(s => s.whocreateid_fx == cuid);
            }

            //###########################################################

            if (searchProd != null)
            {//项目筛选
                requests = requests.Where(s => s.productid_fx == searchProd);
            }
            switch (sortOrder)
            {
                case "Code_desc":
                    requests = requests.OrderByDescending(s => s.code);
                    break;
                case "Code_asc":
                    requests = requests.OrderBy(s => s.code);
                    break;
                case "date_asc":
                    requests = requests.OrderBy(s => s.createdate);
                    break;
                case "date_desc":
                    requests = requests.OrderByDescending(s => s.createdate);
                    break;
                default:
                    requests = requests.OrderBy(s => s.createdate);
                    break;
            }

            return View(requests.ToPagedList(pageNum ?? 1, 5));
        }

        // GET: FLOW_REQUEST/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FLOW_REQUEST fLOW_REQUEST = db.FLOW_REQUEST.Find(id);
            if (fLOW_REQUEST == null)
            {
                return HttpNotFound();
            }
            return View(fLOW_REQUEST);
        }

        // GET: FLOW_REQUEST/Create
        public ActionResult Create()
        {
            List<FLOW_PRODUCT> categories = FLOW_PRODUCT.GETALL();
            ViewData["Categories_prod"] = new SelectList(categories, "id", "name");

            return View();
        }

        // POST: FLOW_REQUEST/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,code,productid_fx,startdate,deadline,request_text,request_file,desc_text,remark,whocreateid_fx,createdate")] FLOW_REQUEST fLOW_REQUEST)
        {
            Model1 ef = new Model1();
            String username = Request.Cookies["username"].Value.ToString();
            String cuuserid = ef.SYS_USER.Where(item => item.account_id == username).First<SYS_USER>().id.ToString();
            var obj = ef.FLOW_REQUEST.Where(item => item.id >= 0);
            int nowcode = 0, maxid = 0;
            if (obj.Count<FLOW_REQUEST>() > 0)
            {
                maxid = obj.Max(item => item.id);
                nowcode = maxid + 1;
            }
            else
            {
                nowcode = 1;
            }

            fLOW_REQUEST.code = "REQ" + nowcode.ToString().PadLeft(5, '0');
            fLOW_REQUEST.createdate = DateTime.Now;
            fLOW_REQUEST.whocreateid_fx = int.Parse(cuuserid);
            if (ModelState.IsValid)
            {
                db.FLOW_REQUEST.Add(fLOW_REQUEST);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            List<FLOW_PRODUCT> categories = FLOW_PRODUCT.GETALL();
            ViewData["Categories_prod"] = new SelectList(categories, "id", "name");
            return View(fLOW_REQUEST);
        }

        // GET: FLOW_REQUEST/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FLOW_REQUEST fLOW_REQUEST = db.FLOW_REQUEST.Find(id);
            if (fLOW_REQUEST == null)
            {
                return HttpNotFound();
            }
            List<FLOW_PRODUCT> categories = FLOW_PRODUCT.GETALL();
            ViewData["Categories_prod"] = new SelectList(categories, "id", "name");
            return View(fLOW_REQUEST);
        }

        // POST: FLOW_REQUEST/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,code,productid_fx,startdate,deadline,request_text,request_file,desc_text,remark,whocreateid_fx,createdate")] FLOW_REQUEST fLOW_REQUEST)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fLOW_REQUEST).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            List<FLOW_PRODUCT> categories = FLOW_PRODUCT.GETALL();
            ViewData["Categories_prod"] = new SelectList(categories, "id", "name");
            return View(fLOW_REQUEST);
        }

        // GET: FLOW_REQUEST/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FLOW_REQUEST fLOW_REQUEST = db.FLOW_REQUEST.Find(id);
            if (fLOW_REQUEST == null)
            {
                return HttpNotFound();
            }
            return View(fLOW_REQUEST);
        }

        // POST: FLOW_REQUEST/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FLOW_REQUEST fLOW_REQUEST = db.FLOW_REQUEST.Find(id);
            db.FLOW_REQUEST.Remove(fLOW_REQUEST);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

devmgr/Views/FLOW_REQUEST/Create.cshtml
@model devmgr.Models.FLOW_REQUEST

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("产品管理", "Index", "FLOW_PRODUCT")</li>
        <li>@Html.ActionLink("需求管理", "Index", "FLOW_REQUEST")</li>
        <li>@Html.ActionLink("客户管理", "Index", "FLOW_CLIENT")</li>
    </ul>
</div>
<h2>添加</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>需求管理</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*<div class="form-group">
            @Html.LabelFor(model => model.code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.code, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.productid_fx, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.productid_fx, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.productid_fx, "", new { @class = "text-danger" })*@
                @{SelectList category = (SelectList)ViewData["Categories_prod"];}
                @Html.DropDownListFor(model => model.productid_fx, category, "--请选择--", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.startdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.startdate, new { htmlAttributes = new { @class = "form-control" ,id = "datepicker1" } })
                @Html.ValidationMessageFor(model => model.startdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.deadline, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.deadline, new { htmlAttributes = new { @class = "form-control" ,id = "datepicker2" } })
                @Html.ValidationMessageFor(model => model.deadline, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.request_text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.request_text, new { htmlAttributes = new { } })
                @Html.ValidationMessageFor(model => model.request_text, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.request_file, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.request_file, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.request_file, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.desc_text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.desc_text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.desc_text, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.whocreateid_fx, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.whocreateid_fx, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.whocreateid_fx, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.createdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.createdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.createdate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="添加" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回列表", "Index")
</div>
<script src="../../Scripts/pikaday.js"></script>
<script>
    var picker = new Pikaday(
    {
        field: document.getElementById('datepicker1'),
        firstDay: 1,
        minDate: new Date('2000-01-01'),
        maxDate: new Date('2020-12-31'),
        yearRange: [1950,2050]
    });
    var picker2 = new Pikaday(
    {
        field: document.getElementById('datepicker2'),
        firstDay: 1,
        minDate: new Date('2000-01-01'),
        maxDate: new Date('2020-12-31'),
        yearRange: [1950, 2050]
    });
</script>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/ueditor-utf8/ueditor.config.js", "~/Scripts/ueditor-utf8/ueditor.all.js")
    <script type="text/javascript">
        var editor = new baidu.editor.ui.Editor({
        UEDITOR_HOME_URL: '/Scripts/ueditor-utf8/',//配置编辑器路径   也可以在ueditor.config.js文件中配置。
        iframeCssUrl: '/Scripts/ueditor-utf8/themes/iframe.css',//样式路径
        // initialContent:'欢迎使用ueditor',//初始化编辑器内容
        autoHeightEnabled:true,//高度自动增长
        initialFrameHeight:400  //配置编辑器的初始高度为400px。
        });
        editor.render('request_text');   //将编辑器装入 ID=Content 的文本域中。
    </script>

}

devmgr/Views/FLOW_REQUEST/Delete.cshtml
@model devmgr.Models.FLOW_REQUEST
@using System.Linq;
@using devmgr.Models;
@{Model1 ef = new Model1(); }
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("产品管理", "Index", "FLOW_PRODUCT")</li>
        <li>@Html.ActionLink("需求管理", "Index", "FLOW_REQUEST")</li>
        <li>@Html.ActionLink("客户管理", "Index", "FLOW_CLIENT")</li>
    </ul>
</div>
<h2>删除</h2>

<h3>确定要删除此条记录?</h3>
<div>
    <h4>需求管理</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productid_fx)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.productid_fx)*@
            @{
                var obj = ef.FLOW_PRODUCT.Where(item1 => item1.id == Model.productid_fx);
            }
            @if (obj.Count<FLOW_PRODUCT>() > 0)
            {
                @Html.Label(obj.First<FLOW_PRODUCT>().name.ToString())
            }
            else
            {

            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.startdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.startdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deadline)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deadline)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.request_text)
        </dt>

        <dd>
            @Html.EditorFor(model => model.request_text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.request_file)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.request_file)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.desc_text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.desc_text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.remark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.remark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.whocreateid_fx)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.whocreateid_fx)
            @{
                var obj2 = ef.SYS_USER.Where(item1 => item1.id == Model.whocreateid_fx);
            }
            @if (obj2.Count<SYS_USER>() > 0)
            {
                @Html.Label(obj2.First<SYS_USER>().cname.ToString())
            }
            else
            {

            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="删除" class="btn btn-default" /> |
            @Html.ActionLink("返回列表", "Index")
        </div>
    }
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/ueditor-utf8/ueditor.config.js", "~/Scripts/ueditor-utf8/ueditor.all.js")
    <script type="text/javascript">
        var editor = new baidu.editor.ui.Editor({
        UEDITOR_HOME_URL: '/Scripts/ueditor-utf8/',//配置编辑器路径   也可以在ueditor.config.js文件中配置。
        iframeCssUrl: '/Scripts/ueditor-utf8/themes/iframe.css',//样式路径
        // initialContent:'欢迎使用ueditor',//初始化编辑器内容
        autoHeightEnabled:true,//高度自动增长
        initialFrameHeight: 400,  //配置编辑器的初始高度为400px。
        toolbars: [[]],
        readonly: true
        });
        editor.render('request_text');   //将编辑器装入 ID=Content 的文本域中。
    </script>

}

devmgr/Views/FLOW_REQUEST/Details.cshtml
@model devmgr.Models.FLOW_REQUEST
@using System.Linq;
@using devmgr.Models;
@{Model1 ef = new Model1(); }
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("产品管理", "Index", "FLOW_PRODUCT")</li>
        <li>@Html.ActionLink("需求管理", "Index", "FLOW_REQUEST")</li>
        <li>@Html.ActionLink("客户管理", "Index", "FLOW_CLIENT")</li>
    </ul>
</div>
<h2>查看</h2>

<div>
    <h4>需求管理</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.productid_fx)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.productid_fx)*@
            @{
                var obj = ef.FLOW_PRODUCT.Where(item1 => item1.id == Model.productid_fx);
            }
            @if (obj.Count<FLOW_PRODUCT>() > 0)
            {
                @Html.Label(obj.First<FLOW_PRODUCT>().name.ToString())
            }
            else
            {

            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.startdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.startdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.deadline)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.deadline)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.request_text)
        </dt>

        <dd>
            @Html.EditorFor(model => model.request_text)
        </dd>

        @*<dt>
            @Html.DisplayNameFor(model => model.request_file)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.request_file)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.desc_text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.desc_text)
        </dd>*@

        <dt>
            @Html.DisplayNameFor(model => model.remark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.remark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.whocreateid_fx)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.whocreateid_fx)*@
            @{
                var obj2 = ef.SYS_USER.Where(item1 => item1.id == Model.whocreateid_fx);
            }
            @if (obj2.Count<SYS_USER>() > 0)
            {
                @Html.Label(obj2.First<SYS_USER>().cname.ToString())
            }
            else
            {

            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("编辑", "Edit", new { id = Model.id }) |
    @Html.ActionLink("返回列表", "Index")
</p>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/ueditor-utf8/ueditor.config.js", "~/Scripts/ueditor-utf8/ueditor.all.js")
    <script type="text/javascript">
        var editor = new baidu.editor.ui.Editor({
        UEDITOR_HOME_URL: '/Scripts/ueditor-utf8/',//配置编辑器路径   也可以在ueditor.config.js文件中配置。
        iframeCssUrl: '/Scripts/ueditor-utf8/themes/iframe.css',//样式路径
        // initialContent:'欢迎使用ueditor',//初始化编辑器内容
        autoHeightEnabled:true,//高度自动增长
        initialFrameHeight: 400,  //配置编辑器的初始高度为400px。
        toolbars: [[]],
        readonly: true
        });
        editor.render('request_text');   //将编辑器装入 ID=Content 的文本域中。
    </script>

}