devmgr/Models/FLOW_PROJMO.cs
namespace devmgr.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Linq;

    [Table("enterpine.FLOW_PROJMO")]
    public partial class FLOW_PROJMO
    {
        public int id { get; set; }

        [StringLength(30)]
        [Display(Name = "编号")]
        public string code { get; set; }

        [StringLength(30)]
        [Display(Name = "名称")]
        public string name { get; set; }

        [Display(Name = "所属项目")]
        public int? projectid_fx { get; set; }

        [Display(Name = "负责人")]
        public int? responserid_fx { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "起始日期")]
        public DateTime? startdate { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "结束日期")]
        public DateTime? enddate { get; set; }

        [StringLength(2000)]
        [Display(Name = "相关文档")]
        [DataType(DataType.MultilineText)]
        public string request_text { get; set; }

        [StringLength(200)]
        [Display(Name = "备注")]

        public string remark { get; set; }
        [Display(Name = "创建者")]
        public int? whocreateid { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "创建日期")]
        public DateTime? createdate { get; set; }

        static public List<FLOW_PROJMO> GETALL()
        {
            Model1 db = new Model1();
            return db.FLOW_PROJMO.ToList();
        }
    }
}

devmgr/Controllers/FLOW_PROJMOController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using devmgr.Models;
using PagedList;
namespace devmgr.Controllers
{
    public class FLOW_PROJMOController : Controller
    {
        private Model1 db = new Model1();

        // GET: FLOW_PROJMO
        public ActionResult Index(string searchName, int? searchProj,string sortOrder,int? pageNum, int? mistatus)
        {
            List<FLOW_PROJECT> categories_proj = FLOW_PROJECT.GETALL();
            ViewData["categories_proj"] = new SelectList(categories_proj, "id", "desc_text");

            ViewBag.CurrentSort = sortOrder;
            ViewBag.CodeSortParm = sortOrder == "Code_asc" ? "Code_desc" : "Code_asc";
            ViewBag.CreatedateSortParm = sortOrder == "date_asc" ? "date_desc" : "date_asc";

            var projmos = from s in db.FLOW_PROJMO
                           select s;
            //#########################################################
            if (Request.Cookies["islogin"] == null)
            {
                Response.Redirect("/Account/Login");
            }
            Model1 ef = new Model1();
            string caid = Request.Cookies["username"].Value.ToString();
            int cuid = ef.SYS_USER.Where(item => item.account_id == caid).First<SYS_USER>().id;
            int? ugid = int.Parse(ef.SYS_USER.Where(item => item.account_id == caid).First<SYS_USER>().usertypeid_fx.ToString());
            int mod1id = ef.SYS_MODULE.Where(item => item.code == "MOD00003").First<SYS_MODULE>().id;
            var obj = ef.SYS_UTYPE_MODULE.Where(item => item.usertypeid_fx == ugid && item.moduleid_fx == mod1id);
            if (obj.First<SYS_UTYPE_MODULE>().isenable == 0)
            {
                //START:与我相关的产品
                var products = from s in db.FLOW_PRODUCT
                               select s;
                products = products.Where(s => s.whocreateid_fx == cuid || s.Responserid_fx == cuid);
                var productids = from s in products
                                 select s.id;
                //END:与我相关的产品
                //START:与我相关的项目
                var projects = from s in db.FLOW_PROJECT
                               select s;
                projects = projects.Where(s => s.whocreateid_fx == cuid || s.responserid_fx == cuid || productids.Contains((int)s.productid_fx));
                var projectsids = from s in projects
                               select s.id;
                //END:与我相关的项目

                int[] pdids = productids.ToArray();
                projmos = from s in projmos
                          where s.whocreateid == ugid || s.responserid_fx == ugid || projectsids.Contains((int)s.projectid_fx)
                           select s;
            }

            if (mistatus == 1)
            {//我创建的
                projmos = projmos.Where(s => s.whocreateid == cuid);
            }
            if (mistatus == 0)
            {//我负责的
                projmos = projmos.Where(s => s.responserid_fx == cuid);
            }
            //###########################################################
            if (searchProj != null)
            {//项目筛选
                projmos = projmos.Where(s => s.projectid_fx == searchProj);
            }
            if (!String.IsNullOrEmpty(searchName))
            {//搜索名称
                projmos = projmos.Where(s => s.name.Contains(searchName));
            }

            switch (sortOrder)
            {
                case "Code_desc":
                    projmos = projmos.OrderByDescending(s => s.code);
                    break;
                case "Code_asc":
                    projmos = projmos.OrderBy(s => s.code);
                    break;
                case "date_asc":
                    projmos = projmos.OrderBy(s => s.createdate);
                    break;
                case "date_desc":
                    projmos = projmos.OrderByDescending(s => s.createdate);
                    break;
                default:
                    projmos = projmos.OrderBy(s => s.createdate);
                    break;
            }

            return View(projmos.ToPagedList(pageNum ?? 1, 5));
        }

        // GET: FLOW_PROJMO/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FLOW_PROJMO fLOW_PROJMO = db.FLOW_PROJMO.Find(id);
            if (fLOW_PROJMO == null)
            {
                return HttpNotFound();
            }
            return View(fLOW_PROJMO);
        }

        // GET: FLOW_PROJMO/Create
        public ActionResult Create()
        {
            List<SYS_USER> categories_user = SYS_USER.GETALL();
            ViewData["Categories_user"] = new SelectList(categories_user, "id", "cname");

            List<FLOW_PROJECT> categories_proj = FLOW_PROJECT.GETALL();
            ViewData["categories_proj"] = new SelectList(categories_proj, "id", "desc_text");

            return View();
        }

        // POST: FLOW_PROJMO/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,code,name,projectid_fx,responserid_fx,startdate,enddate,request_text,remark,whocreateid,createdate")] FLOW_PROJMO fLOW_PROJMO)
        {
            Model1 ef = new Model1();
            String username = Request.Cookies["username"].Value.ToString();
            String cuuserid = ef.SYS_USER.Where(item => item.account_id == username).First<SYS_USER>().id.ToString();
            var obj = ef.FLOW_PROJMO.Where(item => item.id >= 0);
            int nowcode = 0, maxid = 0;
            if (obj.Count<FLOW_PROJMO>() > 0)
            {
                maxid = obj.Max(item => item.id);
                nowcode = maxid + 1;
            }
            else
            {
                nowcode = 1;
            }

            fLOW_PROJMO.code = "PRMO" + nowcode.ToString().PadLeft(5, '0');
            fLOW_PROJMO.createdate = DateTime.Now;
            fLOW_PROJMO.whocreateid = int.Parse(cuuserid);

            if (ModelState.IsValid)
            {
                db.FLOW_PROJMO.Add(fLOW_PROJMO);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            List<SYS_USER> categories_user = SYS_USER.GETALL();
            ViewData["Categories_user"] = new SelectList(categories_user, "id", "cname");

            List<FLOW_PROJECT> categories_proj = FLOW_PROJECT.GETALL();
            ViewData["categories_proj"] = new SelectList(categories_proj, "id", "desc_text");
            return View(fLOW_PROJMO);
        }

        // GET: FLOW_PROJMO/Edit/5
        public ActionResult Edit(int? id)
        {
            List<SYS_USER> categories_user = SYS_USER.GETALL();
            ViewData["Categories_user"] = new SelectList(categories_user, "id", "cname");

            List<FLOW_PROJECT> categories_proj = FLOW_PROJECT.GETALL();
            ViewData["categories_proj"] = new SelectList(categories_proj, "id", "desc_text");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FLOW_PROJMO fLOW_PROJMO = db.FLOW_PROJMO.Find(id);
            if (fLOW_PROJMO == null)
            {
                return HttpNotFound();
            }
            return View(fLOW_PROJMO);
        }

        // POST: FLOW_PROJMO/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,code,name,projectid_fx,responserid_fx,startdate,enddate,request_text,remark,whocreateid,createdate")] FLOW_PROJMO fLOW_PROJMO)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fLOW_PROJMO).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            List<SYS_USER> categories_user = SYS_USER.GETALL();
            ViewData["Categories_user"] = new SelectList(categories_user, "id", "cname");

            List<FLOW_PROJECT> categories_proj = FLOW_PROJECT.GETALL();
            ViewData["categories_proj"] = new SelectList(categories_proj, "id", "desc_text");
            return View(fLOW_PROJMO);
        }

        // GET: FLOW_PROJMO/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            FLOW_PROJMO fLOW_PROJMO = db.FLOW_PROJMO.Find(id);
            if (fLOW_PROJMO == null)
            {
                return HttpNotFound();
            }
            return View(fLOW_PROJMO);
        }

        // POST: FLOW_PROJMO/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            FLOW_PROJMO fLOW_PROJMO = db.FLOW_PROJMO.Find(id);
            db.FLOW_PROJMO.Remove(fLOW_PROJMO);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

devmgr/Views/FLOW_PROJMO/Create.cshtml
@model devmgr.Models.FLOW_PROJMO

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>添加</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>项目模块</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.projectid_fx, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.projectid_fx, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.projectid_fx, "", new { @class = "text-danger" })*@
                @{SelectList categoryproj = (SelectList)ViewData["categories_proj"];}
                @Html.DropDownListFor(model => model.projectid_fx, categoryproj, "--请选择--", new { htmlAttributes = new { @class = "form-control" } })


            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.responserid_fx, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.responserid_fx, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.responserid_fx, "", new { @class = "text-danger" })*@
                @{SelectList categoryuser = (SelectList)ViewData["categories_user"];}
                @Html.DropDownListFor(model => model.responserid_fx, categoryuser, "--请选择--", new { htmlAttributes = new { @class = "form-control" } })


            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.startdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.startdate, new { htmlAttributes = new { @class = "form-control" ,id= "datepicker1" } })
                @Html.ValidationMessageFor(model => model.startdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.enddate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.enddate, new { htmlAttributes = new { @class = "form-control" ,id= "datepicker2" } })
                @Html.ValidationMessageFor(model => model.enddate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.request_text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.request_text, new { htmlAttributes = new {  } })
                @Html.ValidationMessageFor(model => model.request_text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.whocreateid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.whocreateid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.whocreateid, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.createdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.createdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.createdate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="添 加" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返 回", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/ueditor-utf8/ueditor.config.js", "~/Scripts/ueditor-utf8/ueditor.all.js")
    <script type="text/javascript">
            var editor = new baidu.editor.ui.Editor({
            UEDITOR_HOME_URL: '/Scripts/ueditor-utf8/',//配置编辑器路径   也可以在ueditor.config.js文件中配置。
            iframeCssUrl: '/Scripts/ueditor-utf8/themes/iframe.css',//样式路径
            // initialContent:'欢迎使用ueditor',//初始化编辑器内容
            autoHeightEnabled:true,//高度自动增长
            initialFrameHeight:400  //配置编辑器的初始高度为400px。
            });
            editor.render('request_text');   //将编辑器装入 ID=Content 的文本域中。
    </script>
}
<script src="../../Scripts/pikaday.js"></script>
<script>
    var picker = new Pikaday(
    {
        field: document.getElementById('datepicker1'),
        firstDay: 1,
        minDate: new Date('2000-01-01'),
        maxDate: new Date('2020-12-31'),
        yearRange: [1950,2050]
    });
    var picker2 = new Pikaday(
    {
        field: document.getElementById('datepicker2'),
        firstDay: 1,
        minDate: new Date('2000-01-01'),
        maxDate: new Date('2020-12-31'),
        yearRange: [1950, 2050]
    });
</script>

devmgr/Views/FLOW_PROJMO/Delete.cshtml
@model devmgr.Models.FLOW_PROJMO
@using System.Linq;
@using devmgr.Models;
@{Model1 ef = new Model1(); }
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>删除</h2>

<h3>确定要删除此条记录?</h3>
<div>
    <h4>项目模块</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.projectid_fx)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.projectid_fx)*@
            @{
                var obj3 = ef.FLOW_PROJECT.Where(item1 => item1.id == Model.projectid_fx);
            }
            @if (obj3.Count<FLOW_PROJECT>() > 0)
            {
                @Html.Label(obj3.First<FLOW_PROJECT>().desc_text.ToString())
            }
            else
            {

            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.responserid_fx)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.responserid_fx)*@
            @{
                var obj = ef.SYS_USER.Where(item1 => item1.id == Model.responserid_fx);
            }
            @if (obj.Count<SYS_USER>() > 0)
            {
                @Html.Label(obj.First<SYS_USER>().cname.ToString())
            }
            else
            {

            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.startdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.startdate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.enddate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.enddate)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.request_text)
        </dt>

        <dd>
            @Html.EditorFor(model => model.request_text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.remark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.remark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.whocreateid)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.whocreateid)*@
            @{
                var obj2 = ef.SYS_USER.Where(item1 => item1.id == Model.whocreateid);
            }
            @if (obj2.Count<SYS_USER>() > 0)
            {
                @Html.Label(obj2.First<SYS_USER>().cname.ToString())
            }
            else
            {

            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="删除" class="btn btn-default" /> |
            @Html.ActionLink("返回", "Index")
        </div>
    }
</div>
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryval", "~/Scripts/ueditor-utf8/ueditor.config.js", "~/Scripts/ueditor-utf8/ueditor.all.js")
    <script type="text/javascript">
            var editor = new baidu.editor.ui.Editor({
            UEDITOR_HOME_URL: '/Scripts/ueditor-utf8/',//配置编辑器路径   也可以在ueditor.config.js文件中配置。
            iframeCssUrl: '/Scripts/ueditor-utf8/themes/iframe.css',//样式路径
            // initialContent:'欢迎使用ueditor',//初始化编辑器内容
            autoHeightEnabled:true,//高度自动增长
            initialFrameHeight: 400,  //配置编辑器的初始高度为400px。
            toolbars: [[]],
            readonly:true
            });
            editor.render('request_text');   //将编辑器装入 ID=Content 的文本域中。
    </script>
}

devmgr/Views/FLOW_PROJMO/Index.cshtml
@*@model IEnumerable<devmgr.Models.FLOW_PROJMO>*@
@model PagedList.IPagedList<devmgr.Models.FLOW_PROJMO>
@using PagedList.Mvc;

@using System.Linq;
@using devmgr.Models;
@{Model1 ef = new Model1(); }
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>项目模块</h2>

<p>
    @Html.ActionLink("添 加", "Create")
</p>

<span style="background-color: rgb(255, 255, 102);">
    @using (Html.BeginForm("Index", "FLOW_PROJMO", FormMethod.Get, new { @class = "form-inline" }))
    {
        <p>
            模块名称: @Html.TextBox("searchName", null, new { @class = "form-control", @placeholder = "请输入关键字", @style = "width:150px;height:30px;font-size:12px;" })
            &nbsp;所在项目: @Html.DropDownList("searchProj", ViewData["categories_proj"] as SelectList, "请选择项目", new { @style = "width:150px;height:30px;font-size:12px;", @id = "searchProj" })
            &nbsp; &nbsp;  @Html.RadioButton("mistatus", 1) 由我创建 @Html.RadioButton("mistatus", 0) 由我负责 @Html.RadioButton("mistatus", 2, true) 全部
            &nbsp;<input type="submit" value="查询" class="btn btn-default" />
        </p>
    }

</span>

<table class="table">
    <tr>
        <th>
            @Html.ActionLink("编号", "Index", new { sortOrder = ViewBag.CodeSortParm })
        </th>
        <th>
            名称
        </th>
        <th>
            所在项目
        </th>
        <th>
            负责人
        </th>
        <th>
            开始日期
        </th>
        <th>
            截止日期
        </th>
        @*<th>
            @Html.DisplayNameFor(model => model.request_text)
        </th>*@
        <th>
            备注
        </th>
        <th>
            创建者
        </th>
        <th>
            @Html.ActionLink("创建日期", "Index", new { sortOrder = ViewBag.CreatedateSortParm })
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.projectid_fx)
        </td>*@
        <td>
            @{ var obj = ef.FLOW_PROJECT.Where(item1 => item1.id == item.projectid_fx); }
            @if (obj.Count<FLOW_PROJECT>() > 0)
            {
                @Html.Label(obj.First<FLOW_PROJECT>().desc_text.ToString())
            }
            else
            {
                    
            }
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.responserid_fx)
        </td>*@
        <td>
            @{ var obj2 = ef.SYS_USER.Where(item1 => item1.id == item.responserid_fx); }
            @if (obj2.Count<SYS_USER>() > 0)
            {
                @Html.Label(obj2.First<SYS_USER>().cname.ToString())
            }
            else
            {

            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.startdate, "shortdatetime")
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.enddate, "shortdatetime")
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.request_text)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.remark)
        </td>
        <td>
            @{ var obj3 = ef.SYS_USER.Where(item1 => item1.id == item.whocreateid); }
            @if (obj3.Count<SYS_USER>() > 0)
            {
                @Html.Label(obj3.First<SYS_USER>().cname.ToString())
            }
            else
            {


            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.createdate, "shortdatetime")
        </td>
        <td>
            @{
                if (Request.Cookies["islogin"] == null)
                {
                    if (ViewContext.RouteData.Values["controller"].ToString() == "Account" && ViewContext.RouteData.Values["action"].ToString() == "Login")
                    {
                    }
                    else
                    {
                        Response.Redirect("/Account/Login");
                    }
                }
                String caid = Request.Cookies["username"].Value.ToString();
                int cuid = ef.SYS_USER.Where(s => s.account_id == caid).First<SYS_USER>().id;
                int? ugid = int.Parse(ef.SYS_USER.Where(s => s.account_id == caid).First<SYS_USER>().usertypeid_fx.ToString());
                int mod1id = ef.SYS_MODULE.Where(s => s.code == "MOD00003").First<SYS_MODULE>().id;
                var objs = ef.SYS_UTYPE_MODULE.Where(s => s.usertypeid_fx == ugid && s.moduleid_fx == mod1id);
            }
            @if (objs.Count() != 0)
            {
                if (objs.First<SYS_UTYPE_MODULE>().iswrite == 1)
                {
                    @Html.ActionLink("编辑 |", "Edit", new { id = item.id })
                }
            }
            @Html.ActionLink("查看", "Details", new { id = item.id })

            @if (objs.Count() != 0)
            {
                if (objs.First<SYS_UTYPE_MODULE>().iswrite == 1)
                {
                    @Html.ActionLink("| 删除", "Delete", new { id = item.id })
                }
            }
        </td>
    </tr>
}
</table>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
@Html.PagedListPager(Model, pageNum => Url.Action("Index", new { pageNum, categories_proj = ViewData["categories_proj"], sortOrder = ViewBag.CurrentSort }))