devmgr/Models/SYS_DEPART.cs
namespace devmgr.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;
    using System.Linq;
    using System.Web.Mvc;

    public partial class SYS_DEPART
    {
        public int id { get; set; }

        [StringLength(30)]
        [Display(Name = "部门编号")]
        public string code { get; set; }

        [StringLength(20)]
        [Display(Name = "部门名称")]
        [Required(AllowEmptyStrings = false, ErrorMessage = "名称不能为空")]
        [Remote("CheckDepName", "Validate", AdditionalFields = "id")]
        //[Remote("CheckDepName", "Validate")]
        public string name { get; set; }

        [Display(Name = "部门主管")]
        public int? managerid_fx { get; set; }

        [StringLength(100)]
        [Display(Name = "描述")]

        public string desc_text { get; set; }

        [StringLength(200)]
        [Display(Name = "备注")]
        public string remark { get; set; }

        [Display(Name = "由谁创建")]
        public int? whocreateid_fx { get; set; }

        [Column(TypeName = "date")]
        [Display(Name = "创建日期")]
        public DateTime? createdate { get; set; }

        static public List<SYS_DEPART> GETALL() {
            Model1 db = new Model1();
            return db.SYS_DEPART.ToList();
        }
    }
}

devmgr/Controllers/SYS_DEPARTController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using devmgr.Models;

namespace devmgr.Controllers
{
    public class SYS_DEPARTController : Controller
    {
        private Model1 db = new Model1();

        // GET: SYS_DEPART
        public ActionResult Index()
        {
            return View(db.SYS_DEPART.ToList());
        }

        // GET: SYS_DEPART/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SYS_DEPART sYS_DEPART = db.SYS_DEPART.Find(id);
            if (sYS_DEPART == null)
            {
                return HttpNotFound();
            }
            return View(sYS_DEPART);
        }

        // GET: SYS_DEPART/Create
        public ActionResult Create()
        {
            List<SYS_USER> categories = SYS_USER.GETALL();
            ViewData["Categories"] = new SelectList(categories, "id", "cname");

            return View();
        }

        // POST: SYS_DEPART/Create
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,code,name,managerid_fx,desc_text,remark,whocreateid_fx,createdate")] SYS_DEPART sYS_DEPART)
        {
            if (ModelState.IsValid)
            {
                Model1 ef = new Model1();
                String username = Request.Cookies["username"].Value.ToString();
                String cuuserid = ef.SYS_USER.Where(item => item.account_id == username).First<SYS_USER>().id.ToString();
                var obj = ef.SYS_DEPART.Where(item => item.id >= 0);
                int nowcode= 0,maxid=0;
                if (obj.Count<SYS_DEPART>()>0) {
                    maxid=obj.Max(item => item.id);
                    nowcode = maxid + 1; }
                else {
                    nowcode = 1;
                }

                sYS_DEPART.code = "DEP" + nowcode.ToString().PadLeft(5,'0');
                sYS_DEPART.createdate = DateTime.Now;
                sYS_DEPART.whocreateid_fx = int.Parse(cuuserid);

                db.SYS_DEPART.Add(sYS_DEPART);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(sYS_DEPART);
        }

        // GET: SYS_DEPART/Edit/5
        public ActionResult Edit(int? id)
        {
   
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SYS_DEPART sYS_DEPART = db.SYS_DEPART.Find(id);
            if (sYS_DEPART == null)
            {
                return HttpNotFound();
            }

            List<SYS_USER> categories = SYS_USER.GETALL();
            ViewData["Categories"] = new SelectList(categories, "id", "cname");

            return View(sYS_DEPART);
        }

        // POST: SYS_DEPART/Edit/5
        // 为了防止“过多发布”攻击，请启用要绑定到的特定属性，有关 
        // 详细信息，请参阅 http://go.microsoft.com/fwlink/?LinkId=317598。
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,code,name,managerid_fx,desc_text,remark,whocreateid_fx,createdate")] SYS_DEPART sYS_DEPART)
        {
            if (ModelState.IsValid)
            {
                db.Entry(sYS_DEPART).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            List<SYS_USER> categories = SYS_USER.GETALL();
            ViewData["Categories"] = new SelectList(categories, "id", "cname");
            return View(sYS_DEPART);
        }

        // GET: SYS_DEPART/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SYS_DEPART sYS_DEPART = db.SYS_DEPART.Find(id);
            if (sYS_DEPART == null)
            {
                return HttpNotFound();
            }
            return View(sYS_DEPART);
        }

        // POST: SYS_DEPART/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            SYS_DEPART sYS_DEPART = db.SYS_DEPART.Find(id);
            db.SYS_DEPART.Remove(sYS_DEPART);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        

    }
}

devmgr/Views/SYS_DEPART/Create.cshtml
@model devmgr.Models.SYS_DEPART

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("用户管理", "Index", "SYS_USER")</li>
        <li>@Html.ActionLink("部门管理", "Index", "SYS_DEPART")</li>
         
        <li>@Html.ActionLink("用户组管理", "Index", "SYS_USERTYPE")</li>
        <li>@Html.ActionLink("权限管理", "Index", "SYS_UTYPE_MODULE")</li>
    </ul>
</div>
<h2>添加</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>部门管理</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @*<div class="form-group">
            @Html.LabelFor(model => model.code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.code, "", new { @class = "text-danger" })
            </div>
        </div>*@


        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.managerid_fx, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.managerid_fx, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.managerid_fx, "", new { @class = "text-danger" })*@
                @{SelectList category = (SelectList)ViewData["Categories"];}
                @Html.DropDownListFor(model => model.managerid_fx, category, "--请选择--", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.desc_text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.desc_text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.desc_text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.whocreateid_fx, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.whocreateid_fx, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.whocreateid_fx, "", new { @class = "text-danger" })
            </div>
        </div>*@

        @*<div class="form-group">
            @Html.LabelFor(model => model.createdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.createdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.createdate, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="添加" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回列表", "Index")
</div>

<script src="../../Scripts/pikaday.js"></script>
<script>

    var picker = new Pikaday(
    {
        field: document.getElementById('datepicker'),
        firstDay: 1,
        minDate: new Date('2000-01-01'),
        maxDate: new Date('2020-12-31'),
        yearRange: [1950,2050]
    });

</script>

devmgr/Views/SYS_DEPART/Delete.cshtml
@model devmgr.Models.SYS_DEPART
@using System.Linq;
@using devmgr.Models;
@{Model1 ef = new Model1(); }
@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("用户管理", "Index", "SYS_USER")</li>
        <li>@Html.ActionLink("部门管理", "Index", "SYS_DEPART")</li>
         
        <li>@Html.ActionLink("用户组管理", "Index", "SYS_USERTYPE")</li>
        <li>@Html.ActionLink("权限管理", "Index", "SYS_UTYPE_MODULE")</li>
    </ul>
</div>
<h2>删除</h2>

<h3>确定要删除这一项?</h3>
<div>
    <h4>部门管理</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.managerid_fx)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.managerid_fx)*@
            @{
                var obj = ef.SYS_USER.Where(item1 => item1.id == Model.managerid_fx);
            }
            @if (obj.Count<SYS_USER>() > 0)
            {
                @Html.Label(obj.First<SYS_USER>().cname.ToString())
            }
            else
            {

            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.desc_text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.desc_text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.remark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.remark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.whocreateid_fx)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.whocreateid_fx)*@
            @{
                var obj2 = ef.SYS_USER.Where(item1 => item1.id == Model.whocreateid_fx);
            }
            @if (obj2.Count<SYS_USER>() > 0)
            {
                @Html.Label(obj2.First<SYS_USER>().cname.ToString())
            }
            else
            {

            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdate)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="删除" class="btn btn-default" /> |
            @Html.ActionLink("返回列表", "Index")
        </div>
    }
</div>

devmgr/Views/SYS_DEPART/Details.cshtml
@model devmgr.Models.SYS_DEPART
@using System.Linq;
@using devmgr.Models;
@{Model1 ef = new Model1(); }
@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("用户管理", "Index", "SYS_USER")</li>
        <li>@Html.ActionLink("部门管理", "Index", "SYS_DEPART")</li>
         
        <li>@Html.ActionLink("用户组管理", "Index", "SYS_USERTYPE")</li>
        <li>@Html.ActionLink("权限管理", "Index", "SYS_UTYPE_MODULE")</li>
    </ul>
</div>
<h2>查看</h2>

<div>
    <h4>部门管理</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.code)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.code)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.managerid_fx)
        </dt>

        <dd> 
            @*@{ int a = (int)Model.managerid_fx }
            @Html.DisplayFor(model => model.managerid_fx)*@

            @{ 
                    var obj = ef.SYS_USER.Where(item1 => item1.id == Model.managerid_fx);
            }
            @if (obj.Count<SYS_USER>() > 0)
            {
                @Html.Label(obj.First<SYS_USER>().cname.ToString())
            }
            else
            {

            }
           
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.desc_text)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.desc_text)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.remark)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.remark)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.whocreateid_fx)
        </dt>

        <dd>
            @*@Html.DisplayFor(model => model.whocreateid_fx)*@
            @{
                var obj2 = ef.SYS_USER.Where(item1 => item1.id == Model.whocreateid_fx);
            }
            @if (obj2.Count<SYS_USER>() > 0)
            {
                @Html.Label(obj2.First<SYS_USER>().cname.ToString())
            }
            else
            {

            }
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.createdate)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.createdate)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("编辑", "Edit", new { id = Model.id }) |
    @Html.ActionLink("返回列表", "Index")
</p>

devmgr/Views/SYS_DEPART/Edit.cshtml
@model devmgr.Models.SYS_DEPART

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("用户管理", "Index", "SYS_USER")</li>
        <li>@Html.ActionLink("部门管理", "Index", "SYS_DEPART")</li>
         
        <li>@Html.ActionLink("用户组管理", "Index", "SYS_USERTYPE")</li>
        <li>@Html.ActionLink("权限管理", "Index", "SYS_UTYPE_MODULE")</li>
    </ul>
</div>
<h2>编辑</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>部门管理</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.code, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.code, new { htmlAttributes = new { @class = "form-control", @readonly = "true" } })
                @Html.ValidationMessageFor(model => model.code, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control",@readonly = "true" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.managerid_fx, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @*@Html.EditorFor(model => model.managerid_fx, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.managerid_fx, "", new { @class = "text-danger" })*@
                @{SelectList category = (SelectList)ViewData["Categories"];}
                @Html.DropDownListFor(model => model.managerid_fx, category, "--请选择--", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.desc_text, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.desc_text, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.desc_text, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.remark, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.remark, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.remark, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style= "display:none">
            @Html.LabelFor(model => model.whocreateid_fx, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.whocreateid_fx, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.whocreateid_fx, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group"  style= "display:none">
            @Html.LabelFor(model => model.createdate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.createdate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.createdate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="保存" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("返回列表", "Index")
</div>

devmgr/Views/SYS_DEPART/Index.cshtml
@model IEnumerable<devmgr.Models.SYS_DEPART>
@using System.Linq;
@using devmgr.Models;
@{Model1 ef = new Model1(); }
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div class="navbar-collapse collapse">
    <ul class="nav navbar-nav">
        <li>@Html.ActionLink("用户管理", "Index", "SYS_USER")</li>
        <li>@Html.ActionLink("部门管理", "Index", "SYS_DEPART")</li>
         
        <li>@Html.ActionLink("用户组管理", "Index", "SYS_USERTYPE")</li>
        <li>@Html.ActionLink("权限管理", "Index", "SYS_UTYPE_MODULE")</li>
    </ul>
</div>
<h2>部门管理</h2>

<p>
    @Html.ActionLink("添 加", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.code)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.managerid_fx)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.desc_text)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.remark)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.whocreateid_fx)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.createdate)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.code)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.name)
        </td>
        <td>
            @{ var obj = ef.SYS_USER.Where(item1 => item1.id == item.managerid_fx); }
            @if (obj.Count<SYS_USER>() > 0)
            {
                @Html.Label(obj.First<SYS_USER>().cname.ToString())
            }
            else
            {

            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.desc_text)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.remark)
        </td>
        <td>
            @{ var obj2 = ef.SYS_USER.Where(item1 => item1.id == item.whocreateid_fx); }
            @if (obj2.Count<SYS_USER>() > 0)
            {
                @Html.Label(obj2.First<SYS_USER>().cname.ToString())
            }
            else
            {

            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.createdate, "shortdatetime")
        </td>
        <td>
            @{
                if (Request.Cookies["islogin"] == null)
                {
                    if (ViewContext.RouteData.Values["controller"].ToString() == "Account" && ViewContext.RouteData.Values["action"].ToString() == "Login")
                    {
                    }
                    else
                    {
                        Response.Redirect("/Account/Login");
                    }
                }
                String caid = Request.Cookies["username"].Value.ToString();
                int cuid = ef.SYS_USER.Where(s => s.account_id == caid).First<SYS_USER>().id;
                int? ugid = int.Parse(ef.SYS_USER.Where(s => s.account_id == caid).First<SYS_USER>().usertypeid_fx.ToString());
                int mod1id = ef.SYS_MODULE.Where(s => s.code == "MOD00008").First<SYS_MODULE>().id;
                var objs = ef.SYS_UTYPE_MODULE.Where(s => s.usertypeid_fx == ugid && s.moduleid_fx == mod1id);
            }
            @if (objs.Count() != 0)
            {
                if (objs.First<SYS_UTYPE_MODULE>().iswrite == 1)
                {
                    @Html.ActionLink("编辑 |", "Edit", new { id = item.id })
                }
            }
            @Html.ActionLink("查看", "Details", new { id = item.id })

            @if (objs.Count() != 0)
            {
                if (objs.First<SYS_UTYPE_MODULE>().iswrite == 1)
                {
                    @Html.ActionLink("| 删除", "Delete", new { id = item.id })
                }
            }
        </td>
    </tr>
}

</table>